api:
    build: ./env/api/
    ports:
        - "8082:8080"
    links:
        - mongo
        - elasticsearch
    volumes:
        - ./openstore-api:/srv/openstore

web:
    build: ./env/web/
    ports:
        - "8081:8081"
    volumes:
        - ./openstore-web:/srv/openstore

mongo:
    image: mongo:3.4
    ports:
        - "27017:27017"
    volumes:
        - /data/db:/data/db
        - ./openstore-api:/srv/openstore

elasticsearch:
    image: elasticsearch:2-alpine
    ports:
        - "9200:9200"
    volumes:
        - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data

nginx:
    build: ./env/nginx/
    ports:
        - "8080:80"
    links:
        - api
        - web
